import type {Metadata} from "next";
import {ReactNode} from "react";
import {ToastContainer} from "react-toastify";
import CssBaseline from "@mui/material/CssBaseline";
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <CssBaseline/>
        {children}
        <ToastContainer/>
        </body>
        </html>
    );
}
